name = "spin-mama-app-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-app.de"
HMAC_KEY = "080481e827bb8835d1a5cd8599986276a8f229dd2a42130ce030c1c11254fd9c"
COOKIE_NAME = "twa"
PLAY_PATH = "play"
BUTTON_ID = "p463994efdf70b8142e9952bac4f72155"
GATE_SALT = "bb00747401157042"
